name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Use the Node version your app requires

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watchAll=false

    - name: Build
      run: npm run build

    - name: Deploy
      run: echo "Deploy steps go here"
      # Replace this with your actual deployment steps, such as deploying to Vercel, Netlify, or another service.
